// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA17EIccJK0We2AMg15d_1VXZvZquW3LZs',
    appId: '1:71272723322:web:06ebaf1dd7253852d11cc3',
    messagingSenderId: '71272723322',
    projectId: 'notes-app-ee3da',
    authDomain: 'notes-app-ee3da.firebaseapp.com',
    storageBucket: 'notes-app-ee3da.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDitxpsZ42j-MfEOHkZ7v5dQcK2xBVxWEg',
    appId: '1:71272723322:android:fa3453d7e4c9a050d11cc3',
    messagingSenderId: '71272723322',
    projectId: 'notes-app-ee3da',
    storageBucket: 'notes-app-ee3da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAaXhZJAXLOvmZYSTW9st3rd4JvrrLwQ',
    appId: '1:71272723322:ios:778c80b360b45d28d11cc3',
    messagingSenderId: '71272723322',
    projectId: 'notes-app-ee3da',
    storageBucket: 'notes-app-ee3da.firebasestorage.app',
    androidClientId: '71272723322-3th0847cbljofekpm0sbh5qc48nmdq3e.apps.googleusercontent.com',
    iosClientId: '71272723322-24l65vmijofavk4vai4pa96qqbnm18lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAaXhZJAXLOvmZYSTW9st3rd4JvrrLwQ',
    appId: '1:71272723322:ios:778c80b360b45d28d11cc3',
    messagingSenderId: '71272723322',
    projectId: 'notes-app-ee3da',
    storageBucket: 'notes-app-ee3da.firebasestorage.app',
    androidClientId: '71272723322-3th0847cbljofekpm0sbh5qc48nmdq3e.apps.googleusercontent.com',
    iosClientId: '71272723322-24l65vmijofavk4vai4pa96qqbnm18lc.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA17EIccJK0We2AMg15d_1VXZvZquW3LZs',
    appId: '1:71272723322:web:ec6d4f53c62b602cd11cc3',
    messagingSenderId: '71272723322',
    projectId: 'notes-app-ee3da',
    authDomain: 'notes-app-ee3da.firebaseapp.com',
    storageBucket: 'notes-app-ee3da.firebasestorage.app',
  );
}
